wandb_version: 1

train_len:
  desc: null
  value: 256
test_len:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.11.2
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705980681.690629
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.2
      5: 0.16.1
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
